### ISSUE TITLE
Not working on Ubuntu?

### ISSUE THREAD

**Issue by ghost** [numixproject/numix-calendar-icons#4]
Good day, anacron seems to be installed by default on Ubuntu 16.04.1, so I've put the script in the '/etc/cron.daily' directory. Unfortunately it doesn't seems to work for me, is there something else I should do to kickstart the script at boot time?

**Comment by bilelmoussaoui** [comment]
What happens if you run the script by yourself? using ` ./calendar-scripţ`?

**Comment by ghost** [comment]
It runs when I run it as sudo, but the icons for GNOME calendar and Google calendar are the same with '31' in them. Even after I log out and log back in, nothing changed.

**Comment by bilelmoussaoui** [comment]
Alright, which version of Numix Circle/Numix Base are you using? the latest git one?

**Comment by ghost** [comment]
I use the one currently in the PPA, so '201701252032' for the base icon theme and '201611240401' for the circle theme.

**Comment by bilelmoussaoui** [comment]
Alright, this is related to this issue https://github.com/numixproject/numix-core/issues/3573. I will keep this one open until we fix the other one

**Comment by bilelmoussaoui** [comment]
Should be fixed on the latest version of Numix Circle, please wait until a new release is out and reopen if you still can reproduce this issue ;)

**Comment by Foggalong** [comment]
For fyi, the next release will probably be mid next week :smile:
