### ISSUE TITLE
Google Calendar icon unaffected

### ISSUE THREAD

**Issue by ghost** [numixproject/numix-calendar-icons#5]
Good day, now that the PPA was updated with the new circle icons the script indeed does change the icon of GNOME Calendar (red calendar icon), but it does not change the icon for Google Calendar (blue icon). I managed to make the script execute on every system startup with "sudo crontab -e" and adding "@reboot <path to script>" so that part is covered. Can you please look into why the blue calendar icon is not changed? Thank you! The Google Calendar .desktop file name is: "chrome-ejjicmeblgpmajnghnpcppodonldlgfn-Default.desktop" and it is stored in the user home directory at "~/.local/share/applications". Thank you for looking into this.

**Comment by bilelmoussaoui** [comment]
@szekeres2016 It's the same issue as the Red calendar one. Will fix that right now :)

**Comment by bilelmoussaoui** [comment]
@Foggalong i've just fixed this bug on numix-core master (followed the same fix we have did for the red calendar icon for both blue and purple one)
